language: php
before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer self-update
  - composer install --no-interaction
script:
  - cd $TRAVIS_BUILD_DIR
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpcbf --standard=PSR2 src
  - php vendor/bin/phpdoc -d src -t docs --ignore vendor/,docs/,examples/
  # add the SinusBot favicon
  - wget -q -O images/favicon.ico https://sinusbot.github.io/favicon.ico
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: docs
  on:
    branch: master
